name: Installation testing

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: '3.9'
              cache: 'poetry' # caching pip dependencies
          - run: poetry install
          - name: import test on ${{matrix.os}}
            run: |
                cd tests
                cd push_test
                poetry run python import_test.py






